name: Deploy

on: workflow_dispatch
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get last code
        uses: actions/checkout@v2.3.2
      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: d92490.hostru11.fornex.host
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/mitynov.ru/
          port: 21
